In [1]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns 

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [2]:
df=pd.read_csv("Iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [3]:
from sklearn.datasets import load_iris

In [4]:
iris = load_iris()

In [5]:
dir(iris)

['DESCR',
 'data',
 'data_module',
 'feature_names',
 'filename',
 'frame',
 'target',
 'target_names']

In [6]:
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [7]:
iris.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [9]:
species = {0:'setosa',1:'versicolor',2:'virginica'}

In [10]:
iris_df = pd.DataFrame(iris.data)
iris_df

0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]

In [11]:
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['Target'] = iris.target
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [12]:
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [13]:
le = LabelEncoder()
le.fit_transform(df['Species'])

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [14]:
df['Species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [15]:
species_list = df['Species'].unique().tolist()
species_list.sort()
species_list

['Iris-setosa', 'Iris-versicolor', 'Iris-virginica']

In [16]:
iris_df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                  5.1               3.5                1.4               0.2   
1                  4.9               3.0                1.4               0.2   
2                  4.7               3.2                1.3               0.2   
3                  4.6               3.1                1.5               0.2   
4                  5.0               3.6                1.4               0.2   
..                 ...               ...                ...               ...   
145                6.7               3.0                5.2               2.3   
146                6.3               2.5                5.0               1.9   
147                6.5               3.0                5.2               2.0   
148                6.2               3.4                5.4               2.3   
149                5.9               3.0                5.1               1.8   

     Target  
0         0  
1         0  
2         0  
3         0  
4         0  
..      ...  
145       2  
146       2  
147       2  
148       2  
149       2  

[150 rows x 5 columns]

In [17]:
iris_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   Target             150 non-null    int32  
dtypes: float64(4), int32(1)
memory usage: 5.4 KB


In [18]:
iris_df['Target'].value_counts()

0    50
1    50
2    50
Name: Target, dtype: int64

In [19]:
iris_df['Target'].value_counts()/ len(df)*100

0    33.333333
1    33.333333
2    33.333333
Name: Target, dtype: float64

### Model Training

In [20]:
x = iris_df.drop('Target', axis = 1) 
y = iris_df['Target']

x_train, x_test, y_train,y_test = train_test_split(x,y, test_size=0.20, random_state=5, stratify=y)

In [21]:
x_train.shape, x_test.shape, y_train.shape,y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [22]:
model = LogisticRegression(max_iter= 150)
model.fit(x_train,y_train)

LogisticRegression(max_iter=150)

### Model Evaluation

#Testing Data:

In [23]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 2, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 0, 1, 0, 1,
       2, 1, 1, 0, 2, 2, 1, 1])

In [24]:
y_test

36     0
27     0
38     0
105    2
93     1
141    2
9      0
16     0
80     1
94     1
8      0
39     0
86     1
118    2
53     1
124    2
111    2
129    2
47     0
61     1
35     0
92     1
127    2
133    2
57     1
14     0
148    2
122    2
51     1
95     1
Name: Target, dtype: int32

In [25]:
accuracy_score(y_test,y_pred)

0.9666666666666667

In [26]:
confusion_matrix(y_test,y_pred)

array([[10,  0,  0],
       [ 0, 10,  0],
       [ 0,  1,  9]], dtype=int64)

In [27]:
y_test.shape

(30,)

In [28]:
y_test.value_counts()

0    10
2    10
1    10
Name: Target, dtype: int64

In [29]:
from sklearn.metrics import multilabel_confusion_matrix

In [30]:
multilabel_confusion_matrix(y_test,y_pred)

array([[[20,  0],
        [ 0, 10]],

       [[19,  1],
        [ 0, 10]],

       [[20,  0],
        [ 1,  9]]], dtype=int64)

In [31]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [32]:
# Testing Data 

def model_eval(model, x,y):
    y_pred = model.predict(x)
    
    con_mat = confusion_matrix(y,y_pred)
    print(f"Confusion Matrix: \n {con_mat}")
    
    clf_report = classification_report(y,y_pred)
    print(f"Classification Report = \n{clf_report}")
    
    ml_cn = multilabel_confusion_matrix(y,y_pred)
    print(f"Class wise Confusion matrix = \n {ml_cn}")
    
    return "Performance Evaluation"

In [33]:
model_eval(model, x_test,y_test)

Confusion Matrix: 
 [[10  0  0]
 [ 0 10  0]
 [ 0  1  9]]
Classification Report = 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       0.91      1.00      0.95        10
           2       1.00      0.90      0.95        10

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30

Class wise Confusion matrix = 
 [[[20  0]
  [ 0 10]]

 [[19  1]
  [ 0 10]]

 [[20  0]
  [ 1  9]]]


'Performance Evaluation'

In [34]:
model_eval(model, x_train,y_train)

Confusion Matrix: 
 [[40  0  0]
 [ 0 38  2]
 [ 0  0 40]]
Classification Report = 
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        40
           1       1.00      0.95      0.97        40
           2       0.95      1.00      0.98        40

    accuracy                           0.98       120
   macro avg       0.98      0.98      0.98       120
weighted avg       0.98      0.98      0.98       120

Class wise Confusion matrix = 
 [[[80  0]
  [ 0 40]]

 [[80  0]
  [ 2 38]]

 [[78  2]
  [ 0 40]]]


'Performance Evaluation'

##Low Bias & Low Varience :: Generalised Model

In [35]:
model.predict(x_test)

array([0, 0, 0, 2, 1, 2, 0, 0, 1, 1, 0, 0, 1, 2, 1, 2, 2, 2, 0, 1, 0, 1,
       2, 1, 1, 0, 2, 2, 1, 1])

In [36]:
x_test.head(1)

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
36                5.5               3.5                1.3               0.2

In [37]:
model.predict(x_test.head(1))

array([0])

In [38]:
species = {0:'setosa',1:'versicolor',2:'virginica'}

In [39]:
sl = 6.4 
sw = 3.4
pl = 4.5
pw = 1.4

data = [[sl,sw,pl,pw]]
result= model.predict(data)
print(f"Predicted Speices of Iris = {species[result[0]]}")

Predicted Speices of Iris = versicolor


C:\Users\sachi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


In [40]:
import pickle 

with open('logistic_model.pkl','wb') as file: 
    pickle.dump(model,file)

In [41]:
import json 

with open('species.json','w') as file: 
    json.dump(species, file)

In [42]:
len(x.columns)

4

In [43]:
columns = {"Column Names":x.columns.tolist()}

with open('columns_names.json','w') as file: 
    json.dump(columns,file)

In [44]:
data = df.tail(1).values.tolist()
data

[[150, 5.9, 3.0, 5.1, 1.8, 'Iris-virginica']]

In [45]:
species = {0:'setosa',1:'versicolor',2:'virginica'}

In [46]:
with open(r'C:\Users\sachi\Desktop\Velocity\Train_Models\Iris_model\artifacts\logistic_model.pkl','rb') as model_file: 
    model = pickle.load(model_file)
    
with open(r'C:\Users\sachi\Desktop\Velocity\Train_Models\Iris_model\artifacts\columns_names.json','r') as col_file: 
    column_names = json.load(col_file)
    
user_input = np.zeros(len(column_names['Column Names']))

#array = np.array(column_names['Column Names'])

SepalLengthCm = 5.9
SepalWidthCm = 3.0
PetalLengthCm = 5.1
PetalWidthCm = 1.8

user_input[0] = SepalLengthCm
user_input[1] = SepalWidthCm
user_input[2] = PetalLengthCm
user_input[3] = PetalWidthCm

print(f"{user_input=}")
Species = {0:'setosa',1:'versicolor',2:'virginica'}
Species= model.predict([user_input])

# if Species==0:
#     print(f"Predicted Species = Iris-setosa")
# if Species==1:
#     print(f"Predicted Species = Iris-versicolor")
# if Species==2:
#     print(f"Predicted Species = Iris-virginica")
# print(f"Actual Species = Iris-virginica")
print(f"Predicted Speices of Iris = {species[Species[0]]}")

user_input=array([5.9, 3. , 5.1, 1.8])
Predicted Speices of Iris = virginica


C:\Users\sachi\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
